import { db } from '../config/database';
import { bids, bidItems, tenders } from '../schema';
import { eq, and, desc, sql } from 'drizzle-orm';
import { auditService } from './audit.service';
import { notificationService } from './notification.service';
import type { RequestUser, NewBid, NewBidItem } from '../types';

export const bidService = {
  async listByVendor(vendorOrgId: string) {
    return db.select().from(bids)
      .where(eq(bids.vendor_org_id, vendorOrgId))
      .orderBy(desc(bids.created_at));
  },

  async listByTender(tenderId: string) {
    return db.select().from(bids)
      .where(eq(bids.tender_id, tenderId))
      .orderBy(desc(bids.created_at));
  },

  async getById(id: string) {
    const [bid] = await db.select().from(bids).where(eq(bids.id, id)).limit(1);
    return bid ?? null;
  },

  async create(data: Omit<NewBid, 'bid_number'>, user: RequestUser) {
    // Validate deadline
    const [tender] = await db.select().from(tenders)
      .where(eq(tenders.id, data.tender_id))
      .limit(1);

    if (!tender) throw new Error('Tender not found');
    if (new Date() > new Date(tender.submission_deadline)) {
      throw new Error('Submission deadline has passed');
    }

    const [bid] = await db.insert(bids).values({
      ...data,
      bid_number: '', // Auto-generated by trigger
      vendor_org_id: user.org_id!,
      submitted_by: user.id,
    }).returning();

    await auditService.log(
      user.id, user.org_id, 'CREATE_BID', 'bid', bid.id,
      `Created bid for tender ${tender.tender_number}`,
    );

    return bid;
  },

  async update(id: string, data: Partial<NewBid>, user: RequestUser) {
    const bid = await this.getById(id);
    if (!bid) throw new Error('Bid not found');
    if (bid.status !== 'draft') throw new Error('Only draft bids can be edited');

    const [updated] = await db.update(bids).set({
      ...data,
      updated_at: new Date(),
    }).where(eq(bids.id, id)).returning();

    await auditService.log(
      user.id, user.org_id, 'UPDATE_BID', 'bid', id,
      `Updated draft bid ${updated.bid_number}`,
    );

    return updated;
  },

  async getItems(bidId: string) {
    return db.select().from(bidItems)
      .where(eq(bidItems.bid_id, bidId))
      .orderBy(bidItems.bid_id, bidItems.id);
  },

  async addItems(bidId: string, items: NewBidItem[]) {
    return db.insert(bidItems).values(items.map(item => ({
      ...item,
      bid_id: bidId,
    }))).returning();
  },

  async submit(id: string, user: RequestUser) {
    const bid = await this.getById(id);
    if (!bid) throw new Error('Bid not found');
    if (bid.status !== 'draft') throw new Error('Only draft bids can be submitted');

    // Validate deadline again at submission time
    const [tender] = await db.select().from(tenders)
      .where(eq(tenders.id, bid.tender_id)).limit(1);
    if (new Date() > new Date(tender.submission_deadline)) {
      throw new Error('Submission deadline has passed');
    }

    // Calculate total from line items
    const items = await db.select().from(bidItems).where(eq(bidItems.bid_id, id));
    const total = items.reduce((sum, item) => {
      return sum + Number(item.unit_price) * Number(item.quantity);
    }, 0);

    const [updated] = await db.update(bids).set({
      status: 'submitted',
      submitted_at: new Date(),
      total_amount: total.toFixed(2),
      updated_at: new Date(),
    }).where(eq(bids.id, id)).returning();

    // Notify procurer
    await notificationService.sendBidSubmitted(updated, tender);

    await auditService.log(
      user.id, user.org_id, 'SUBMIT_BID', 'bid', id,
      `Submitted bid ${updated.bid_number} for ${tender.tender_number}`,
      { total_amount: total },
    );

    return updated;
  },

  async withdraw(id: string, user: RequestUser) {
    const [updated] = await db.update(bids).set({
      status: 'withdrawn',
      withdrawn_at: new Date(),
      updated_at: new Date(),
    }).where(eq(bids.id, id)).returning();

    await auditService.log(
      user.id, user.org_id, 'WITHDRAW_BID', 'bid', id,
      `Withdrew bid ${updated.bid_number}`,
    );

    return updated;
  },
};