import { db } from '../config/database';
import { tenders, tenderItems, tenderInvitations, tenderDocuments, tenderAssignments } from '../schema';
import { eq, and, sql, desc, ilike, inArray } from 'drizzle-orm';
import { auditService } from './audit.service';
import { notificationService } from './notification.service';
import type { NewTender, RequestUser, PaginatedResponse, Tender } from '../types';

export const tenderService = {
  async list(user: RequestUser, filters: {
    status?: string;
    search?: string;
    page?: number;
    pageSize?: number;
  }): Promise<PaginatedResponse<Tender>> {
    const page = filters.page ?? 1;
    const pageSize = filters.pageSize ?? 20;
    const offset = (page - 1) * pageSize;

    let query = db.select().from(tenders).$dynamic();

    // Role-based filtering
    if (user.role === 'super_admin') {
      // See everything
    } else if (['pe_admin'].includes(user.role)) {
      query = query.where(eq(tenders.buyer_org_id, user.org_id!));
    } else {
      // tagged_only — see assigned tenders
      const assignments = await db.select({ tender_id: tenderAssignments.tender_id })
        .from(tenderAssignments)
        .where(eq(tenderAssignments.user_id, user.id));
      const tenderIds = assignments.map(a => a.tender_id);
      if (tenderIds.length === 0) return { data: [], total: 0, page, pageSize, totalPages: 0 };
      query = query.where(inArray(tenders.id, tenderIds));
    }

    if (filters.status) {
      query = query.where(eq(tenders.status, filters.status as any));
    }
    if (filters.search) {
      query = query.where(ilike(tenders.title, `%${filters.search}%`));
    }

    const data = await query.orderBy(desc(tenders.created_at)).limit(pageSize).offset(offset);

    const [{ count }] = await db.select({ count: sql<number>`count(*)` }).from(tenders);

    return {
      data: data as Tender[],
      total: Number(count),
      page,
      pageSize,
      totalPages: Math.ceil(Number(count) / pageSize),
    };
  },

  async getById(id: string) {
    const [tender] = await db.select().from(tenders).where(eq(tenders.id, id)).limit(1);
    return tender ?? null;
  },

  async create(data: Omit<NewTender, 'tender_number'>, user: RequestUser) {
    // tender_number is auto-generated by PostgreSQL trigger
    const [tender] = await db.insert(tenders).values({
      ...data,
      tender_number: '', // Trigger will overwrite
      buyer_org_id: user.org_id!,
      created_by: user.id,
    }).returning();

    await auditService.log(
      user.id, user.org_id, 'CREATE_TENDER', 'tender', tender.id,
      `Created tender ${tender.tender_number}`,
    );

    return tender;
  },

  async update(id: string, data: Partial<Tender>, user: RequestUser) {
    const [updated] = await db.update(tenders)
      .set({ ...data, updated_at: new Date() })
      .where(eq(tenders.id, id))
      .returning();

    await auditService.log(
      user.id, user.org_id, 'UPDATE_TENDER', 'tender', id,
      `Updated tender ${updated.tender_number}`,
    );

    return updated;
  },

  async publish(id: string, user: RequestUser) {
    const [updated] = await db.update(tenders)
      .set({
        status: 'published',
        is_published: true,
        published_at: new Date(),
        updated_at: new Date(),
      })
      .where(eq(tenders.id, id))
      .returning();

    // Send notifications to invited vendors
    const invitations = await db.select().from(tenderInvitations)
      .where(eq(tenderInvitations.tender_id, id));

    for (const inv of invitations) {
      await notificationService.sendTenderPublished(updated, inv.vendor_org_id);
    }

    await auditService.log(
      user.id, user.org_id, 'PUBLISH_TENDER', 'tender', id,
      `Published tender ${updated.tender_number} to ${invitations.length} vendors`,
    );

    return updated;
  },

  async close(id: string, user: RequestUser) {
    const [updated] = await db.update(tenders)
      .set({ status: 'closed', updated_at: new Date() })
      .where(eq(tenders.id, id))
      .returning();

    await auditService.log(
      user.id, user.org_id, 'CLOSE_TENDER', 'tender', id,
      `Closed tender ${updated.tender_number}`,
    );

    return updated;
  },

  async forward(id: string, toStage: string, toUserId: string, notes: string, user: RequestUser) {
    const [updated] = await db.update(tenders)
      .set({
        status: toStage as any,
        current_stage: toStage,
        forwarded_to: toUserId,
        forwarded_at: new Date(),
        updated_at: new Date(),
      })
      .where(eq(tenders.id, id))
      .returning();

    await auditService.log(
      user.id, user.org_id, 'FORWARD_TENDER', 'tender', id,
      `Forwarded tender to ${toStage}`, { notes },
    );

    return updated;
  },

  async delete(id: string, user: RequestUser) {
    await db.delete(tenders).where(eq(tenders.id, id));
    await auditService.log(
      user.id, user.org_id, 'DELETE_TENDER', 'tender', id,
      `Deleted tender`,
    );
  },

  // ── Withhold ──────────────────────────────────────────────────

  async withhold(id: string, reason: string, user: RequestUser) {
    const [updated] = await db.update(tenders)
      .set({
        status: 'withheld',
        updated_at: new Date(),
      })
      .where(eq(tenders.id, id))
      .returning();

    await auditService.log(
      user.id, user.org_id, 'WITHHOLD_TENDER', 'tender', id,
      `Withheld tender ${updated.tender_number}`, { reason },
    );

    return updated;
  },

  // ── Line Items ────────────────────────────────────────────────

  async getItems(tenderId: string) {
    return db.select().from(tenderItems)
      .where(eq(tenderItems.tender_id, tenderId))
      .orderBy(tenderItems.item_number);
  },

  async addItems(tenderId: string, items: Array<{
    item_number: number;
    description: string;
    unit: string;
    quantity: number;
    estimated_unit_price?: number;
    specifications?: object;
  }>, user: RequestUser) {
    const inserted = await db.insert(tenderItems)
      .values(items.map(item => ({
        tender_id: tenderId,
        item_number: item.item_number,
        description: item.description,
        unit: item.unit,
        quantity: item.quantity,
        estimated_unit_price: item.estimated_unit_price ?? null,
        specifications: item.specifications ?? null,
      })) as never)
      .returning();

    await auditService.log(
      user.id, user.org_id, 'ADD_TENDER_ITEMS', 'tender', tenderId,
      `Added ${inserted.length} line items`,
    );

    return inserted;
  },

  // ── Invitations ───────────────────────────────────────────────

  async getInvitations(tenderId: string) {
    return db.select().from(tenderInvitations)
      .where(eq(tenderInvitations.tender_id, tenderId))
      .orderBy(tenderInvitations.created_at);
  },

  async invite(tenderId: string, vendorOrgIds: string[], user: RequestUser) {
    const inserted = await db.insert(tenderInvitations)
      .values(vendorOrgIds.map(orgId => ({
        tender_id: tenderId,
        vendor_org_id: orgId,
        invited_by: user.id,
      })))
      .returning();

    await auditService.log(
      user.id, user.org_id, 'INVITE_VENDORS', 'tender', tenderId,
      `Invited ${inserted.length} vendor organisations`,
    );

    return inserted;
  },

  // ── Award Decision ────────────────────────────────────────────

  async award(id: string, data: { bid_id: string; notes?: string }, user: RequestUser) {
    const [updated] = await db.update(tenders)
      .set({
        status: 'awarded',
        updated_at: new Date(),
        ...({ awarded_at: new Date(), awarded_bid_id: data.bid_id } as Record<string, unknown>),
      })
      .where(eq(tenders.id, id))
      .returning();

    await auditService.log(
      user.id, user.org_id, 'AWARD_TENDER', 'tender', id,
      `Awarded tender ${updated.tender_number} to bid ${data.bid_id}`,
      { bid_id: data.bid_id, notes: data.notes },
    );

    return updated;
  },
};